server:
  ssl:
    enabled: true
    key-alias: spring-https
    key-store: classpath:javatechie.jks
    key-store-type: JKS
    key-password: password

  port: 7777

  #keytool -genkey -alias spring-https -storetype JKS -keyalg RSA -keysize 2048 -validity 365 -keystore javatechie.jks
  #Command to generate the certificate